### ISSUE TITLE
Bug: Can't remove one player from the push slot

### ISSUE THREAD

**Issue by Tezexlo** [puremana/ME-bot#11]
I don't know where exactly the bug sits, but I can't remove one Player from the push slot (bot respond with: cant find player in push) even when I c&p his name.

**Comment by puremana** [comment]
The bug is to do with the user entering having spaces at the start of their username. For example `$in     puremana`

I will trim this in the future, thank you for the bug report!

**Comment by puremana** [comment]
f36fb071c875d687acc0e07200cf4aff93e0fe4d
