### ISSUE TITLE
start/end push command

### ISSUE THREAD

**Issue by ImperialUser** [puremana/ME-bot#12]
It would be nice to have a start/stop set of commands, so if a push was coming to an end it would allow all other features except !signup and !joinqueue would be disabled with a response like "Sorry but the push is coming to an end and the bot is not accepting any more signups at this time"

**Comment by puremana** [comment]
Great idea, will implement this after finishing what I'm working on now.

**Comment by puremana** [comment]
Thanks again for the suggestion, has now been added.
7bda909f7f53ae90ea112232e5727cf9dafd40c8
