### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Drok00** [puremana/ME-bot#4]
Have time markers and opt-in roles to notify when parties are released and when the 36 hour window is closed. Would like user level role management to the @weeklies role. 

at 12pm Seattle time (when parties are created) ping an opt-in role group @weeklies that parties are released, and 36 hours later a post to declare to @EmpireLeadership that the 36 hour window is closed.

**Comment by puremana** [comment]
Alright cool. There is already an opt-in weeklies role that uses `$weekliesadd` and `$weekliesremove` so I will just be adding that to the help function and then adding the pings

**Comment by puremana** [comment]
https://github.com/puremana/ME-bot/commit/e25194a43a4bc547e6c732e5c06c9257a2cafee8

Done. Let me know how it goes!
