### ISSUE TITLE
FR: %in, %out, %queuejoin, %queueleave without name

### ISSUE THREAD

**Issue by Tezexlo** [puremana/ME-bot#6]
If you type %in or %out without a name, the bot uses your Discord name, for the list (or remove your top listing for the removal).

It's way more convenient for the pusher and most time I don't care for the exact name witch joins (aside from %signup of course).

**Comment by puremana** [comment]
This is a good idea. The only downside is that since people tend to have long names which include all of their alt names, so leaders will need to copy and paste names from the list to do any of the leader commands.

I'll be implementing this in the next version 👍

**Comment by puremana** [comment]
227019df6d2263c1199353e416f97a25c6672f04
