### ISSUE TITLE
FR: redundant commands

### ISSUE THREAD

**Issue by Tezexlo** [puremana/ME-bot#7]
Add some redundant commands for continents:
"queue" for "queuejoin"
"leave" for "queueleave"

Maybe even only some letters for the often used commands to use for the experienced pusher:
i (in), o (out), s (signup), q (queuejoin), l (queueleave, its a small L), st (senttop)...

**Comment by puremana** [comment]
Good idea, will implement in next version 👍

**Comment by puremana** [comment]
191315bc8c2720433380add26b17c00f4cbe0f63

Added the 'queue' and 'leave' commands. I think single character commands could be confusing for people watching and overall not necessary (at least in its current state).
