### ISSUE TITLE
FR: New command to delete msgs

### ISSUE THREAD

**Issue by Tezexlo** [puremana/ME-bot#8]
"delete [number]" (or prune for the tatsumaki user ;) )to delete the last (not pinned) post, like the tatsumaki bot do

I have tatsumaki in the channel, just for this command

**Comment by puremana** [comment]
Will do! Thanks for that idea.

**Comment by puremana** [comment]
13dada08394508c492551f4a2b2d36ec682cd3eb

Can now purge messages in push channels using the purge command. It is used like `$purge 10`, where 10 is the number of messages you want to delete. You will only be able to delete up to the push embed message.
